version: '3.3'

services:
    nodeserver:
        container_name: graphqlcontacts
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ${data}:/usr/src/app
        environment:
            TZ: 'Europe/Madrid'
        ports:
            - "5001:5001"
                       
